#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"
CONF_FILE="/usr/local/etc/nginx/conf.d/dokku-${APP}.conf"
NGINX_PID_FILE="/run/nginx.pid"

if [[ -f "$CONF_FILE" ]]; then
  rm -f "$CONF_FILE"
  dokku_log_info1 "synology-proxy: removed nginx conf for $APP"

  if [[ -f "$NGINX_PID_FILE" ]]; then
    nginx -s reload
    dokku_log_info1 "synology-proxy: nginx reloaded"
  fi
else
  dokku_log_info1 "synology-proxy: no nginx conf found for $APP, nothing to remove"
fi
